chartConfig:
  config:
    conditionalFormattings: []
    label: Members
    selectedField: member_profile_total_members
    showBigNumberLabel: true
  type: big_number
contentType: chart
description: Total count of distinct member firms
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions: []
  exploreName: member_profile
  filters: {}
  limit: 500
  metricOverrides: {}
  metrics:
    - member_profile_total_members
  sorts: []
  tableCalculations: []
  timezone: project_timezone
name: Members
slug: member-count-tile
spaceSlug: jmea-demo
tableConfig:
  columnOrder:
    - member_profile_total_members
tableName: member_profile
verification: null
version: 1
